require('./bootstrap');

import { App, plugin } from '@inertiajs/inertia-vue'
import Vue from 'vue'
import vuetify from "./vuetify";
import VueI18n from 'vue-i18n'


Vue.use(plugin)
Vue.use(VueI18n)
const messages = {
    en: {
        "cancel": 'Cancel',
        "OK": 'OK',
        "confirm": "Confirm",
        "Are you sure you want to delete this record?": "Are you sure you want to delete this record?",
        "no Image":"no Image",
        "name":"Name",
        "Language":"Language",
        "Dashboard": "Dashboard",
        "Menus": "Menus",
        "Slides": "Slides",
        "Users": "Users",
        "Products": "Products",
        "Roles": "Roles",
        "Role": "Role",
        "Add new Product": "Add new Product",
        "Add new Role": "Add new Role",
        "Add new Menu": "Add new Menu",
        "Add new Brand": "Add new Brand",
        "Add new Model": "Add new Model",
        "Product was deleted": "Product was deleted",
        "Product was updated": "Product was updated",
        "Product was saved" : "Product was saved",
        "Settings": "Settings",
        "Update": "Update",
        "Drop files here...": "Drop files here...",
        "category": " Category",
        "Delete": "Delete",
        "Brands" : "Brands",
        "Brand": "Brand",
        "Models": "Models",
        "Model": "Model",
        "New Menu": "New Menu",
        "New Brand": "New Brand",
        "New Model": "New Model",
        "New Product": "New Product",
        "New Role": "New Role",
        "Save": "Save",
        "Back": "Back",
        "Parent": "Parent",
        "Icon": "Icon",
        "Select a category": "Select a category",
        "TopSlider": "TopSlider",
        "FirstSlider": "FirstSlider",
        "SecondSlider":"SecondSlider",
        "ThirdSlider": "ThirdSlider",
        "Detail": "Detail",
        "Email": "Email",
        "Phone": "Phone",
        "Address": "Address",
        "Price": "Price",
        "Quantity": "Quantity",
        "Image": "Image",
        "Description": "Description",
        "Size": "Size",
        "Home": "Home",
        "Fast Delivery": "Fast Delivery",
        "Favorites": "Favorites",
        "My Basket": "My Basket",
        "Profile": "Profile",
      },
    tkm: {
        "cancel": 'Yok',
        "OK": 'Bass',
        "confirm": "Tassykla",
        "Are you sure you want to delete this record?": "Sen Uwerynmy?",
        "no Image":"Surat Yok",
        "name":"Ady",
        "Language":"Dil",
        "Dashboard": "Dolandyryş paneli",
        "Menus": "Kategoriýalar",
        "Slides": "Slaýdlar",
        "Users": "Ulanyjylar",
        "Products": "Önümler",
        "Roles": "Rollar",
        "Role": "Roly",
        "Add new Product": "Täze önüm goş",
        "Add new Role": "Täze rol goş",
        "Add new Menu": "Täze menýu goş",
        "Add new Brand": "Täze marka goş",
        "Add new Model": "Täze model goşuň",
        "Product was deleted": "Önüm Yoklandy",
        "Product was updated": "Önüm Täzelendi",
        "Product was saved" : "Täze  Önüm Goşuldy",
        "Settings": "Sazlamalar",
        "Update": "Täzele",
        "Drop files here...": "Suratlary şu yere taşla...",
        "category": " Kategoriyasy",
        "Delete": "ýokla",
        "Brands" : "Markalar",
        "Brand": "Marka",
        "Models": "Modeller",
        "Model": "Modeli",
        "New Menu": "Täze menýu",
        "New Brand": "Täze marka",
        "New Model": "Täze model",
        "New Product": "Täze önüm",
        "New Role": "Täze Rol",
        "Save": "Sakla",
        "Back": "Yza",
        "Parent": "Degişli kategoriýa",
        "Icon": "Nyşan",
        "Select a category": "Kategoriýa saýla",
        "TopSlider": "Baş slaýder",
        "FirstSlider": "Ilkinji slaýder",
        "SecondSlider":"Ikinji slaýder",
        "ThirdSlider": "Üçünji slaýder",
        "Detail": "Görkez",
        "Email": "Email",
        "Phone": "Telefony",
        "Address": "Adresi",
        "Price": "Bahasy",
        "Quantity": "Mukdary",
        "Image": "Suraty",
        "Description": "Önüm hakda",
        "Size": "Razmeri",
        "Home": "Baş sahypa",
        "Fast Delivery": "Göni ýolla ",
        "Favorites": "Saýlamalar",
        "My Basket": "Sepedim",
        "Profile": "Hasabym",

      },
    ru: {
      "cancel": 'Oтменить',
      "OK": 'Ok',
      "confirm": "подтвердить",
      "Are you sure you want to delete this record?": "Вы уверены, что хотите удалить эту запись?",
      "no Image":"нет изображения",
      "name":"Hазвание",
      "Language":"Язык",
      "Dashboard": "Контрольная Панель",
      "Menus": "Категории",
      "Slides": "Слайды",
      "Users": "Ulanyjylar",
      "Products": "Önümler",
      "Roles": "Rollar",
      "Role": "Role",
      "Add new Product": "Täze önüm goş",
      "Add new Role": "Taze rol goş",
      "Product was deleted": "Önüm Yoklandy",
      "Product was updated": "Önüm Tazelendi",
      "Product was saved" : "Taze  Önüm Goşuldy",
      "Add new Brand": "Add new Brand",
      "Add new Model": "Add new Model",
      "Settings": "Sazlamalar",
      "Update": "Tazele",
      "Drop files here...": "Suratlary şu yere taşla...",
      "category": " Kategoriyasy",
      "Delete": "Удалить",
      "Brands" : "Brands",
      "Brand": "Brand",
      "Models": "Modeller",
      "Model": "Model",
      "New Menu": "New Menu",
      "New Brand": "New Brand",
      "New Model": "New Model",
      "New Product": "New Product",
      "New Role": "New Role",
      "Save": "Save",
      "Back": "Back",
      "Parent": "Parent",
      "Icon": "Nyşan",
      "Select a category": "Select a category",
      "TopSlider": "TopSlider",
      "FirstSlider": "FirstSlider",
      "SecondSlider":"SecondSlider",
      "ThirdSlider": "ThirdSlider",
      "Detail": "Detail",
      "Email": "Email",
      "Phone": "Phone",
      "Address": "Address",
      "Price": "Price",
      "Quantity": "Quantity",
      "Image": "Image",
      "Description": "Description",
      "Size": "Size",
      "Home": "Home",
      "Fast Delivery": "Fast Delivery",
      "Favorites": "Favorites",
      "My Basket": "My Basket",
      "Profile": "Profile",


      }
  }
  const i18n = new VueI18n({
    locale: 'en',
    messages,
  })

const el = document.getElementById('app')
export const bus = new Vue();


new Vue({
    vuetify,
    i18n: i18n,
    render: h => h(App, {
        props: {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: name => require(`./Pages/${name}`).default,
        },
    }),
}).$mount(el)
